module.exports = {
  DB: "postgres",
  SOLANA_WEB3_KEY_WORD: "solana/web3.js",
  NATIVE_KEY_WORD: "solana-program",
  ANCHOR_KEY_WORD: "anchor-lang",
  ANCHOR_WEB3_KEY_WORD: "serum/anchor",
  METAPLEX_KEY_WORD: "metaplex/js",
  GO_KEY_WORD: "gagliardetto/solana",
  DOT_NET_KEY_WORD: "Solnet.Rpc",
  WEB3_JS_TYPE: "web3.js",
  ANCHOR_JS_TYPE: "anchor.js",
  NFT_TYPE: "nft",
  GO_TYPE: "go",
  NATIVE_TYPE: "native",
  ANCHOR_TYPE: "anchor",
  DOT_NET_TYPE: "dotnet",
};